// Copyright 2025 Juspay Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Release views are saved dimension filters. Users create them by hand ("custom"), and Airborne
//! creates one for every release's dimension set ("auto_generated") so each slice that has ever
//! been released is browsable without rebuilding the filter.

use std::collections::{BTreeMap, BTreeSet, HashMap};

use diesel::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

use crate::types as airborne_types;
use crate::utils::db::{models::ReleaseViewEntry, schema::hyperotaserver::release_views, DbPool};
use crate::{run_blocking, types::ABError};

use release_views::dsl::{
    app_id, dimensions as dimensions_col, id, name, org_id,
    pending_delete_release_id as pending_delete_col, view_type as view_type_col,
};

/// Name given to the auto-generated view of a release that targets no dimensions.
pub const DEFAULT_VIEW_NAME: &str = "default";

#[derive(Serialize, Deserialize, Debug, Clone, Copy, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ReleaseViewType {
    /// Created by a user.
    #[default]
    Custom,
    /// Created by Airborne from a release's dimensions.
    AutoGenerated,
}

impl ReleaseViewType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Custom => "custom",
            Self::AutoGenerated => "auto_generated",
        }
    }
}

impl From<&str> for ReleaseViewType {
    fn from(value: &str) -> Self {
        match value {
            "auto_generated" => Self::AutoGenerated,
            _ => Self::Custom,
        }
    }
}

/// Dimension values reach us as arbitrary JSON but a view filter is always compared as a string
/// (that is how `x-dimension` carries it), so scalars keep their plain form and anything else
/// falls back to its compact JSON encoding.
fn value_to_filter_string(value: &Value) -> String {
    match value {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

/// Sorted key/value pairs — the canonical form both the name and the stored filter derive from,
/// so the same dimension set always yields the same view regardless of map ordering.
fn canonicalise(dimensions: &HashMap<String, Value>) -> BTreeMap<String, String> {
    dimensions
        .iter()
        .map(|(key, value)| (key.clone(), value_to_filter_string(value)))
        .collect()
}

pub fn view_name_for(dimensions: &BTreeMap<String, String>) -> String {
    if dimensions.is_empty() {
        return DEFAULT_VIEW_NAME.to_string();
    }
    dimensions
        .iter()
        .map(|(key, value)| format!("{}={}", key, value))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The `[{"key": ..., "value": ...}]` shape the `release_views.dimensions` column stores.
pub fn view_dimensions_json(dimensions: &BTreeMap<String, String>) -> Value {
    Value::Array(
        dimensions
            .iter()
            .map(|(key, value)| serde_json::json!({ "key": key, "value": value }))
            .collect(),
    )
}

/// Order-independent identity of a stored filter, used to tell whether a view already covers a
/// dimension set. Views created through the API keep the user's row order, so the raw JSON can
/// differ while the filter is the same.
fn fingerprint(dimensions: &Value) -> BTreeSet<(String, String)> {
    dimensions
        .as_array()
        .map(|entries| {
            entries
                .iter()
                .filter_map(|entry| {
                    let object = entry.as_object()?;
                    let key = object.get("key")?.as_str()?.to_string();
                    let value = object.get("value").map(value_to_filter_string)?;
                    Some((key, value))
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Creates the auto-generated view for a release's dimensions, unless a view already covers that
/// exact set. Returns the new view, or `None` when one already existed.
pub async fn ensure_auto_generated_view(
    pool: DbPool,
    organisation: String,
    application: String,
    dimensions: &HashMap<String, Value>,
) -> airborne_types::Result<Option<ReleaseViewEntry>> {
    let canonical = canonicalise(dimensions);
    let view_name = view_name_for(&canonical);
    let view_dimensions = view_dimensions_json(&canonical);
    let target = fingerprint(&view_dimensions);

    run_blocking!({
        let mut conn = pool.get()?;

        let existing = release_views::table
            .filter(app_id.eq(&application))
            .filter(org_id.eq(&organisation))
            .load::<ReleaseViewEntry>(&mut conn)
            .map_err(|e| {
                ABError::InternalServerError(format!("Failed to list release views: {}", e))
            })?;

        if existing
            .iter()
            .any(|view| fingerprint(&view.dimensions) == target)
        {
            return Ok(None);
        }

        // A concurrent release for the same dimensions may have inserted this name already; the
        // unique (app_id, org_id, name) constraint makes that a no-op rather than an error.
        let inserted = diesel::insert_into(release_views::table)
            .values((
                id.eq(Uuid::new_v4()),
                app_id.eq(&application),
                org_id.eq(&organisation),
                name.eq(&view_name),
                dimensions_col.eq(&view_dimensions),
                view_type_col.eq(ReleaseViewType::AutoGenerated.as_str()),
            ))
            .on_conflict((app_id, org_id, name))
            .do_nothing()
            .get_result::<ReleaseViewEntry>(&mut conn)
            .optional()
            .map_err(|e| {
                ABError::InternalServerError(format!("Failed to create release view: {}", e))
            })?;

        Ok(inserted)
    })
}

/// Inverse of [`view_dimensions_json`] — turns a stored filter back into a context map usable as a
/// Superposition experiment context. Values are strings because that is how a view stores them; the
/// only dimension schema Airborne supports today is `string`, so nothing is lost.
pub fn view_dimensions_to_context(dimensions: &Value) -> HashMap<String, Value> {
    fingerprint(dimensions)
        .into_iter()
        .map(|(key, value)| (key, Value::String(value)))
        .collect()
}

/// Records that `release_id` is the delete release that will retire this view once it concludes.
pub async fn mark_delete_release_pending(
    pool: DbPool,
    view_id: Uuid,
    release_id: String,
) -> airborne_types::Result<()> {
    run_blocking!({
        let mut conn = pool.get()?;
        diesel::update(release_views::table.filter(id.eq(&view_id)))
            .set(pending_delete_col.eq(Some(&release_id)))
            .execute(&mut conn)
            .map_err(|e| {
                ABError::InternalServerError(format!("Failed to mark pending deletion: {}", e))
            })?;
        Ok(())
    })
}

/// Resolves the view waiting on `release_id`: removes it when the deletion actually took effect
/// (the release concluded on its experimental variant), otherwise just clears the marker so the
/// slice can be deleted again later. No-op when no view is waiting on that release.
pub async fn settle_pending_delete(
    pool: DbPool,
    organisation: String,
    application: String,
    release_id: String,
    remove_view: bool,
) -> airborne_types::Result<()> {
    run_blocking!({
        let mut conn = pool.get()?;
        let waiting = release_views::table
            .filter(app_id.eq(&application))
            .filter(org_id.eq(&organisation))
            .filter(pending_delete_col.eq(&release_id));

        if remove_view {
            diesel::delete(waiting).execute(&mut conn).map_err(|e| {
                ABError::InternalServerError(format!("Failed to remove release view: {}", e))
            })?;
        } else {
            diesel::update(waiting)
                .set(pending_delete_col.eq(None::<String>))
                .execute(&mut conn)
                .map_err(|e| {
                    ABError::InternalServerError(format!("Failed to clear pending deletion: {}", e))
                })?;
        }
        Ok(())
    })
}

/// `(view id, view name, release id)` for every view with a delete release in flight.
pub async fn pending_delete_releases(
    pool: DbPool,
    organisation: String,
    application: String,
) -> airborne_types::Result<Vec<(Uuid, String, String)>> {
    run_blocking!({
        let mut conn = pool.get()?;
        let rows = release_views::table
            .filter(app_id.eq(&application))
            .filter(org_id.eq(&organisation))
            .filter(pending_delete_col.is_not_null())
            .select((id, name, pending_delete_col))
            .load::<(Uuid, String, Option<String>)>(&mut conn)
            .map_err(|e| {
                ABError::InternalServerError(format!("Failed to list pending deletions: {}", e))
            })?;

        Ok(rows
            .into_iter()
            .filter_map(|(view_id, view_name, release_id)| {
                release_id.map(|release_id| (view_id, view_name, release_id))
            })
            .collect())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dims(pairs: &[(&str, Value)]) -> HashMap<String, Value> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.clone()))
            .collect()
    }

    #[test]
    fn name_is_sorted_and_stable() {
        let a = canonicalise(&dims(&[
            ("os", Value::String("android".into())),
            ("city", Value::String("blr".into())),
        ]));
        let b = canonicalise(&dims(&[
            ("city", Value::String("blr".into())),
            ("os", Value::String("android".into())),
        ]));

        assert_eq!(view_name_for(&a), "city=blr, os=android");
        assert_eq!(view_name_for(&a), view_name_for(&b));
    }

    #[test]
    fn name_falls_back_to_default_without_dimensions() {
        assert_eq!(view_name_for(&canonicalise(&HashMap::new())), "default");
    }

    #[test]
    fn non_string_values_keep_their_json_form() {
        let canonical = canonicalise(&dims(&[
            ("build", Value::from(42)),
            ("beta", Value::Bool(true)),
        ]));
        assert_eq!(view_name_for(&canonical), "beta=true, build=42");
    }

    #[test]
    fn fingerprint_ignores_entry_order() {
        let generated = view_dimensions_json(&canonicalise(&dims(&[
            ("os", Value::String("ios".into())),
            ("city", Value::String("blr".into())),
        ])));
        let user_created = serde_json::json!([
            { "key": "os", "value": "ios" },
            { "key": "city", "value": "blr" },
        ]);

        assert_eq!(fingerprint(&generated), fingerprint(&user_created));
    }

    #[test]
    fn context_round_trips_through_the_stored_filter() {
        let original = dims(&[
            ("os", Value::String("android".into())),
            ("city", Value::String("blr".into())),
        ]);
        let stored = view_dimensions_json(&canonicalise(&original));

        assert_eq!(view_dimensions_to_context(&stored), original);
    }

    #[test]
    fn fingerprint_separates_different_filters() {
        let android = view_dimensions_json(&canonicalise(&dims(&[(
            "os",
            Value::String("android".into()),
        )])));
        let ios =
            view_dimensions_json(&canonicalise(&dims(&[("os", Value::String("ios".into()))])));

        assert_ne!(fingerprint(&android), fingerprint(&ios));
    }
}
