blank_issues_enabled: false
contact_links:
  - name: Feature Request 💡
    url: https://https://github.com/juspay/airborne/tree/main/airborne-react-plugin/discussions/new?category=ideas
    about: If you have a feature request, please create a new discussion on GitHub.
  - name: Discussions on GitHub 💬
    url: https://https://github.com/juspay/airborne/tree/main/airborne-react-plugin/discussions
    about: This library works as promised but if you need help, please ask questions here.
