services:
  postgres:
    image: postgres:15
    container_name: hyper-ota-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-hyperotaserver}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    # Resource optimization for development
    shm_size: 256mb

  superposition:
    image: ghcr.io/juspay/superposition-demo:${SUPERPOSITION_VERSION:-0.79.1}
    container_name: superposition
    ports:
      - "${SUPERPOSITION_PORT:-8080}:8080"
    # volumes:
    #   - init-data:/init-data # Shared volume to pass the env file
    restart: unless-stopped

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER:-keycloak}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${KEYCLOAK_DB_PORT:-5434}:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT:-8180}:8080"
      - "${KEYCLOAK_METRICS_PORT:-9000}:9000"
    depends_on:
      keycloak-db:
        condition: service_healthy
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
      - --metrics-enabled=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 30s

  localstack:
    image: localstack/localstack:${LOCALSTACK_VERSION:-latest}
    container_name: hyper-ota-localstack
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
    # Add persistent volume for LocalStack data
    volumes:
      - ./localstack-data:/var/lib/localstack
      # - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SERVICES=${LOCALSTACK_SERVICES:-kms,s3}
      - DEBUG=${LOCALSTACK_DEBUG:-1}
      - PERSISTENCE=1 # Enable persistence
      - DATA_DIR=/var/lib/localstack/data
    ports:
      - "7566:4566" # LocalStack Gateway
    healthcheck:
      # Check specific services that we need (kms and s3)
      test: >-
        awslocal kms list-keys &&
        awslocal s3 ls
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:
  keycloak_postgres_data:
  init-data: # Define the shared volume
